services:
  excalibur:
    build: .
    image: ghcr.io/williamjacksn/excalibur
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./.local:/home/python/excalibur

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/excalibur
    init: true
    volumes:
      - ./:/home/python/docker-excalibur
    working_dir: /home/python/docker-excalibur
